// hi-vue-assessment/src/App.vue
<script setup>
// App component with RouterView and Suspense wrapper
// The Suspense boundary is provided — use it with async components and lazy-loaded routes
</script>

<template>
  <div class="app">
    <header class="app-header">
      <h1>HI Assessment</h1>
      <!-- TODO: Add navigation links using <RouterLink> -->
    </header>

    <main>
      <!-- Suspense boundary is provided — use it with lazy-loaded routes -->
      <RouterView v-slot="{ Component }">
        <Suspense>
          <template #default>
            <component :is="Component" />
          </template>
          <template #fallback>
            <div class="loading">Loading...</div>
          </template>
        </Suspense>
      </RouterView>
    </main>
  </div>
</template>

<style scoped>
.app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 1rem;
}

.app-header {
  padding: 1rem 0;
  margin-bottom: 2rem;
  border-bottom: 1px solid #e0e0e0;
}

.loading {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 200px;
  font-size: 1.2rem;
  color: #666;
}
</style>

// hi-react-assessment/src/App.jsx
import { Suspense, lazy } from 'react';
import { Routes, Route } from 'react-router-dom';

// TODO: Use React.lazy() to code-split your page components
// Example: const Home = lazy(() => import('./pages/Home'));
import Home from './pages/Home';
import Detail from './pages/Detail';

function App() {
  return (
    <div className="app">
      <header className="app-header">
        <h1>HI Assessment</h1>
        {/* TODO: Add navigation links */}
      </header>

      <main>
        {/* Suspense boundary is provided — use it with lazy-loaded routes */}
        <Suspense fallback={<div className="loading">Loading...</div>}>
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/detail/:id" element={<Detail />} />
          </Routes>
        </Suspense>
      </main>
    </div>
  );
}

export default App;
